name: Release

on:
  push:
    # tags:
    #   - '*'  # 当有新标签被推送到仓库时触发工作流
permissions:
  contents: write # 授予写入仓库内容的权限

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 检出代码到工作区

      - name: Verify Git repository
        run: |
          if [ ! -d ".git" ]; then
            echo "Git repository is not initialized."
            exit 1
          fi

      - name: Set Git user information
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          echo "Git 用户邮箱: $(git config --global user.email)"
          echo "Git 用户名: $(git config --global user.name)"

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # 选择合适的 Node.js 版本
          cache: 'pnpm'  # 缓存 pnpm 依赖

      - name: Install dependencies
        run: pnpm install  # 使用 pnpm 安装项目依赖

      - name: Run release script
        run: pnpm run release  # 使用 pnpm 执行版本发布脚本